Us1 c styling update#65
gisellemartel/CONPASS pull request #101
Opened 2020-03-21 21:09 UTC by GD-Dheer

All required corrections are complete: 
 - Campus switch should be pill shaped
 - Semi-transparent (opacity/fill)
 - Current campus should be highlighted

2020-03-21 21:17 UTC, eufekt requested changes
I am getting weird rendering both on android and ios. The buttons appear on top of the search bar. Please fix
![IMG_4424 2](https://user-images.githubusercontent.com/30513164/77236750-c3f3f400-6b97-11ea-9e1d-6689a733cd8d.PNG)

2020-03-21 21:45 UTC, trevornag commented
Just tried it. I am getting the same issue as @Nichita-Hariton. I glanced at the code and for the most for the CSS, I see percentages but try as much as possible to use percentages rather than concrete values i.e. 44. This has caused styling issues in the past whereby it looks good on one device but completely off on another. Perhaps changing properties to % will solve this problem

2020-03-21 21:46 UTC, trevornag requested changes

2020-03-21 21:46 UTC, trevornag commented on components/switchCampuses/styles.js
> +  },
maybe replace concrete values with percentages

2020-03-21 23:44 UTC, GD-Dheer commented
Updated. Verified and working on different Iphone

2020-03-22 01:19 UTC, eufekt approved these changes
COde looks good, please run  ```$yarn lint:fix``` to get rid of spaces

2020-03-22 01:28 UTC, mohhef approved these changes
Required corrections are made. It seems to work fine.

2020-03-22 09:20 UTC, gisellemartel requested changes
Tested on a iPhone XR seems to be issues with the UI. Please refer to screenshot: 
![IMG_1250](https://user-images.githubusercontent.com/32080571/77246372-df451a80-6bfc-11ea-85c1-e8af5b60a6b4.PNG)

2020-03-22 18:53 UTC, eufekt approved these changes
Please fix iphone xr latest issue. Approved.

2020-03-24 14:28 UTC, trevornag approved these changes

2020-03-25 00:31 UTC, gisellemartel approved these changes

2020-03-25 00:31 UTC, merged