US4D
gisellemartel/CONPASS pull request #108
Opened 2020-03-26 05:47 UTC by eufekt

Merged latest from master.
Added interior mode.

If you are having issues with android related to fitToCoordinates animation. Please comment these highlighted lines located in `map/index.js`
<img width="520" alt="Screen Shot 2020-03-26 at 1 42 46 AM" src="https://user-images.githubusercontent.com/30513164/77614548-a01c0f80-6f03-11ea-87f6-6825237b6602.png">

2020-03-26 13:46 UTC, trevornag requested changes
Looks great and works very well. However can we get some unit tests?

2020-03-27 12:07 UTC, trevornag commented
I like it. It works well and looks clean. The code looks good too.

2020-03-27 12:08 UTC, trevornag approved these changes

2020-03-28 02:16 UTC, Belize22 approved these changes
Satisfies acceptance criteria. Code quality is on point.

2020-03-28 03:38 UTC, merged